# Generated by Django 3.2.4 on 2021-06-25 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foot_size', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model_num', models.CharField(max_length=255, unique=True)),
                ('shoe_size', models.CharField(max_length=255)),
                ('size_standard', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='OwnShoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
                ('model_num', models.CharField(max_length=255, unique=True)),
                ('shoe_size', models.CharField(max_length=255)),
                ('size_standart', models.CharField(max_length=4)),
                ('user_pk', models.ForeignKey(db_column='User_pk', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
