# Generated by Django 3.2.5 on 2021-07-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnShoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('shoe_size', models.CharField(max_length=255)),
                ('size_standard', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'OwnShoes',
            },
        ),
        migrations.CreateModel(
            name='ShoesDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_id', models.CharField(max_length=255)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('foot_size', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('shoe_size', models.CharField(max_length=255)),
                ('size_standard', models.CharField(max_length=4)),
                ('size_ratio', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'ShoesDataset',
            },
        ),
    ]
