# Generated by Django 3.2.4 on 2021-06-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_size', '0002_auto_20210625_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownshoes',
            old_name='size_standart',
            new_name='size_standard',
        ),
    ]
