# Generated by Django 3.2.5 on 2021-07-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_size', '0003_alter_shoesdataset_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesdataset',
            name='size_standard',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
