# Generated by Django 3.2.4 on 2021-06-30 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoe_size', '0003_rename_size_standart_ownshoes_size_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownshoes',
            name='user_pk',
            field=models.ForeignKey(db_column='user_pk', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
