# Generated by Django 3.2.5 on 2021-07-09 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_size', '0004_alter_shoesdataset_size_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('reviewer_pk', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoesdataset',
            name='reviewer_id',
        ),
        migrations.AddField(
            model_name='shoesdataset',
            name='reviewer_pk',
            field=models.ForeignKey(db_column='reviewer_pk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoe_size.reviewer'),
        ),
    ]
