# Generated by Django 3.2.5 on 2021-07-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_size', '0005_auto_20210709_2028'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reviewer',
            table='Reviewer',
        ),
    ]
