# Generated by Django 3.2.4 on 2021-06-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='User_pk',
            new_name='user_pk',
        ),
    ]
