# Generated by Django 3.2.4 on 2021-06-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0002_rename_user_pk_user_user_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foot_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
